FROM jboss/keycloak:latest

ENV DB_VENDOR MYSQL
ENV DB_ADDR mysql
ENV DB_DATABASE keycloak
ENV DB_USER keycloak
ENV DB_PASSWORD password
ENV KEYCLOAK_USER admin
ENV KEYCLOAK_PASSWORD Pa55w0rd

COPY src/main/docker/keycloack/import-realm.json /opt/jboss/keycloak/

ENTRYPOINT [ "/opt/jboss/tools/docker-entrypoint.sh" ]
CMD ["-b", "0.0.0.0", "-Dkeycloak.import=/opt/jboss/keycloak/import-realm.json"]