version: '3.7'

services:
  jk33-hw-client:
    container_name: jk33-hw-client
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - SERVER_URL=${SERVER_URL}
